services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - prod-db-data:/var/lib/postgresql/data

  app:
    image: ghcr.io/hammadul92/jobber-backend:${IMAGE_TAG}
    restart: always
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - static-files:/app/static
    depends_on:
      - db

  frontend:
    image: ghcr.io/hammadul92/jobber-frontend:${IMAGE_TAG}
    restart: always
    # Removed the static volume mount for React build
    volumes:
      - /etc/letsencrypt/live/getcontractorz.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/getcontractorz.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

volumes:
  prod-db-data:
  static-files:
